name: mediaplayer_example
description: "Demonstrates how to use the mediaplayer plugin."
publish_to: "none"

environment:
  sdk: ">=3.7.0"
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter

  http: any
  flutter_subtitle: any
  inview_notifier_list: any
  set_state_async: any
  mediaplayer:
    # When depending on this package from a real application you should use:
    #   mediaplayer: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../

dev_dependencies:
  flutter_lints: any

flutter:
  uses-material-design: true
  assets:
    - videos/