name: mediaplayer
description: "A lightweight media player with subtitle rendering and track selection support, leveraging system or app-level components for seamless playback."
version: 1.2.1
repository: "https://github.com/xxoo/mediaplayer"
issue_tracker: "https://github.com/xxoo/mediaplayer/issues"
topics:
  - audio
  - video
  - media
  - player
  - hls

environment:
  sdk: ">=3.3.0"
  flutter: ">=3.28.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_lints: any

flutter:
  plugin:
    platforms:
      web:
        fileName: src/plugin.web.dart
        pluginClass: MediaplayerPlugin
      android:
        package: dev.xx.mediaplayer
        pluginClass: MediaplayerPlugin
      ios:
        pluginClass: MediaplayerPlugin
      macos:
        pluginClass: MediaplayerPlugin
      linux:
        pluginClass: MediaplayerPlugin
      windows:
        pluginClass: MediaplayerPluginCApi
